name = "shop"
main = "worker.js"
compatibility_date = "2026-07-01"

[[kv_namespaces]]
binding = "GoodShop"
id = "c02c733b05854a2da99d2711a1a21947"

[[kv_namespaces]]
binding = "Shop"
id = "b05710f50ec6435b901585da722ee7a6"

# 路由加/*匹配所有接口路径
[[routes]]
pattern = "shop.zztxer.dpdns.org"
custom_domain = true